#!/usr/bin/env bash
# Displays "Best School" 10 times
# On the 9th time, also prints "Hi" on the next line

i=1
while [ "$i" -le 10 ]
do
  echo "Best School"
  if [ "$i" -eq 9 ]; then
    echo "Hi"
  fi
  i=$((i + 1))
done
